<template>
  <div>
    <!-- Title -->
    <h2 style="text-align: center">
      Software Job Applications Tracker (<span style="color: limegreen">{{
        job_apps.length
      }}</span>
      applied)
    </h2>

    <!-- Num Rejections and Pending -->
    <h4 style="line-height: 1.6">
      Pending:
      <span style="color: limegreen">{{ statistics.num_inprogress }}</span>
      <br />
      Rejections:
      <span style="color: red">{{ statistics.num_rejections }}</span>
    </h4>

    <!-- Daily applied count -->
    <section v-if="job_apps">
      <div v-for="(value, key) in job_map" :key="key">
        <span style="font-weight: 400">{{ key }}</span
        >: {{ value }}
      </div>
    </section>

    <!-- Jobs applied -->
    <hr />
    <div v-for="(japp, index) in job_apps" :key="index">
      <!-- Company name -->
      <h2>{{ index + 1 }}. {{ japp.a }}</h2>
      <h4>
        <!-- Position title -->
        <span style="color: blue">{{ japp.b }}</span>
        <!-- Application status -->
        (<span v-if="japp.d" style="color: limegreen">In Progress</span>
        <span v-else style="color: red">Rejected</span>)
        <!-- Dates applied and rejected -->
        <i v-if="japp.e">Applied: {{ japp.e }}</i>
        <i v-if="japp.f">| Rejected: {{ japp.f }}</i>
      </h4>
      <!-- Job requirements -->
      <div style="line-height: 1.75">
        <span v-for="(duty, index) in japp.c" :key="index">
          {{ duty }},&nbsp;
        </span>
      </div>
      <hr />
    </div>
  </div>
</template>

<script>
export default {
  name: "JobApps",
  data() {
    return {
      job_map: null,
      statistics: {
        num_rejections: 0,
        num_inprogress: 0,
      },
      job_apps: [
        {
          a: "PlayStation Global",
          b: "Full Stack Software Engineer II (Contract Role)",
          c: [
            "jQuery",
            "Java",
            "Spring Framework",
            "Spring Boot",
            "JavaScript",
            "React.js",
            "Redux",
            "MySQL",
            "AWS",
            "NoSQL",
            "Node.js",
            "Redis",
            "DynamoDB",
            "BS",
            "Git",
            "CI/CD",
            "API",
          ],
          d: true,
        },
        {
          a: "Activision Blizzard Entertainment",
          b: "Software Engineer, WoW Classic",
          c: ["C++", "C#", "MySQL", "Oracle", "Lua"],
          d: false,
        },
        {
          a: "SpaceX",
          b: "Full Stack Software Engineer (Starlink)",
          c: [
            "HTML",
            "CSS",
            "TypeScript",
            "BS",
            "Python",
            "C#",
            ".NET",
            "Go",
            "Scala",
            "Python",
            "Java",
            "Docker",
            "Kubernetes",
            "React",
            "Angular",
            "JavaScript",
            "PostgreSQL",
            "SQL Server",
            "CI/CD",
            "Gradle",
            "pip",
            "npm",
            "UNIX",
          ],
          d: false,
        },
        {
          a: "Apple",
          b: "Software Security Engineer",
          c: [
            "BS",
            "C",
            "C++",
            "Containerized Server Applications",
            "Deployment",
            "Security",
          ],
          d: true,
        },
        {
          a: "Alphatec Spine",
          b: "Software Engineer I, AIX",
          c: [
            "C#",
            ".NET Core",
            "Unit Tests",
            "OOP",
            "SOLID",
            "Embedded Systems",
            "WPF",
            "SQL",
            "NoSQL",
            "ORM",
            "EFCore",
            "CI/CD",
            "Git",
            "Azure",
            "DevOps",
            "C++",
            "xUnit",
            "nUnit",
            "Python",
            "JavaScript",
            "Agile",
            "Prism",
            "Routing",
            "Data Binding",
            "Hibernate",
            "Dependency Injection",
          ],
          d: true,
        },
        {
          a: "OpenAI | San Francisco, California",
          b: "Software Engineer, Backend",
          c: null,
          d: true,
        },
        {
          a: "Actalent",
          b: "Software Test Engineer",
          c: ["BS", "Python", "C#", "Internship experience"],
          d: false,
        },
        {
          a: "Aviation Training Consulting | Albuquerque, New Mexico",
          b: "Associate Web Developer",
          c: [
            "BS",
            "1 year experience",
            "JavaScript",
            "JQuery",
            "HTML",
            "CSS",
            "XML",
            "Microsoft Office",
            "Photoshop",
            "Dreamweaver",
            "Illustrator",
            "2D animation",
            "Mobile",
          ],
          d: true,
        },
        {
          a: "Rocket Software | Bentonville, Arkansas",
          b: "Software Engineer I",
          c: ["Java", "Minimal professional software engineering experience"],
          d: true,
        },
        {
          a: "Discovery Education | Charlotte, North Carolina",
          b: "Software Engineer",
          c: [
            "Web applications",
            "2+ years of production back-end experience",
            "Python",
            "Flask",
            "SQL",
            "MS SQL Server",
            "MongoDB",
            "Redis",
            "Kubernetes",
            "Docker",
            "i18n",
            "ML",
            "NLP",
            "BS",
            "Elastic Search",
            "Memcached",
            "AWS",
            "EC2",
            "Lambda",
            "Terraform",
          ],
          d: true,
        },
        {
          a: "Kforce Inc | Phoenix, Arizona",
          b: "Java Development Engineer 1",
          c: [
            "BS",
            "Java",
            "1 to 2 years of experience",
            "ReactJS",
            "Next.js",
            "HTML",
            "CSS",
            "JavaScript",
            "Data Structures",
            "Algorithms",
            "Software Design",
            "AWS",
            "Terraforms",
            "Git",
            "Bitbucket",
            "AEM",
            "AEP",
            "Unit Testing",
          ],
          d: true,
        },
        {
          a: "AESC | Carlsbad, California",
          b: "Software Engineer",
          c: [
            "BS",
            "6+ years experience",
            ".NET",
            "C#",
            "ASP.NET",
            "MVC",
            "Angular",
            "JavaScript",
            "SQL Server",
            "Azure",
            "DevOps",
            "Full-Stack",
            "Testing",
            "Software Maintenance",
            "Collaborate",
          ],
          d: true,
          e: "5/3/2024",
        },
        {
          a: "Community Health Accreditation Partner | Riverside, California",
          b: "Software Engineer (.NET)",
          c: [
            "BS",
            "MS preferred",
            ".NET",
            "MVC",
            "Entity Framework",
            "C#",
            "jQuery",
            ".NET Core",
            "React JS",
            "SQL",
            "Microsoft Power Platform",
            "Cloud Flows",
            "Dataflows",
            "Canvas applications",
          ],
          d: true,
          e: "5/3/2024",
        },
        {
          a: "Cognizant Technology Solutions | Lake Forest, California",
          b: "Associate - Software Development Engineer",
          c: [
            "BS",
            "1-4 years experience",
            "API",
            "C#",
            ".NET",
            "WPF",
            "WinForms",
            "Agile",
            "SQL",
            "C++",
            ".NET Core",
            ".NET Standard",
            "Windows",
            "Linux OS",
            "Azure DevOps",
            "Git",
            "TFVC",
          ],
          d: true,
          e: "5/3/2024",
        },
        {
          a: "Microsoft | Redmond, Washington",
          b: "Software Engineering",
          c: [
            "BS",
            "C",
            "C++",
            "C#",
            "Java",
            "JavaScript",
            "Python",
            "Debugging",
            "WebUI3",
            "XAML",
            "Web UI Frameworks",
          ],
          d: true,
          e: "5/4/2024",
        },
        {
          a: "Walgreens | Bellevue, Washington",
          b: "Software Engineer (Frontend, JavaScript, React)",
          c: [
            "BS",
            "2 years experience",
            "APIs",
            "Moblie applications",
            "SDLC",
            "Agile",
            "JavaScript",
            "React",
            "Azure",
            "AWS",
            "GCP",
            "Java",
            "Python",
            "C#",
          ],
          d: true,
          e: "5/6/2024",
        },
        {
          a: "U-Haul | Remote",
          b: "Mobile API Developer",
          c: [
            "3+ years experience",
            "C#",
            ".NET",
            "WebAPI",
            "SOAP",
            "REST",
            "OpenAPI",
            "API",
            "JSON",
            "SQL",
            "Git",
            "Source Control",
            "Visual Studio",
            "Debugging",
            "Unit/Integration Tests",
            "ELK Stack",
            "Kafka",
            "Postman",
            "Azure API",
            "Android",
            "iOS",
          ],
          d: false,
          e: "5/6/2024",
          f: "5/8/2024",
        },
        {
          a: "Upstart Network, Inc. | Remote",
          b: "Software Engineer, Home Lending",
          c: [
            "1+ year experience",
            "Kotlin",
            "Java",
            "C#",
            "JavaScript",
            "React",
            "SQL",
            "AWS",
            "Kafka",
            "Spring Boot",
            "Next.js",
            "Kubernetes",
            "Jira",
          ],
          d: true,
          e: "5/7/2024",
        },
        {
          a: "RSI | United States",
          b: "Software Engineer",
          c: [
            "BS",
            "1-3 years experience",
            "Agile",
            "SDLC",
            "OOD",
            "C#",
            "Entity Framework",
            "REST",
            "Azure",
            "AWS",
            "React",
            "JavaScript",
            "SQL",
          ],
          d: true,
          e: "5/7/2024",
        },
        {
          a: "Complex | Los Angeles, California",
          b: "Software Engineer",
          c: [
            "React",
            "ReactNative",
            "TypeScript",
            "3 years experience",
            "APIs",
          ],
          d: true,
          e: "5/8/2024",
        },
        {
          a: "Orange County Water District | Fountain Valley, California",
          b: "Programmer/Analyst",
          c: [
            "BS",
            "SQL Server",
            "C#",
            ".NET",
            "HTML",
            "JavaScript",
            "C Driver License",
            "3 years experience",
            "Web development",
          ],
          d: true,
          e: "5/8/2024",
        },
        {
          a: "IBISWorld | Los Angeles, California",
          b: "Software Developer",
          c: [
            "5+ years experience",
            "BS",
            "ASP.NET",
            ".NET Core",
            "VB.NET",
            "C#",
            "Visual Studio 2008-2019",
            "SQL Server",
            "XML",
            "JSON",
            "HTML",
            "CSS",
            "JavaScript",
            "JQuery",
            "MVC",
            "WebForms",
            "Azure",
            "DevOps",
            "Git",
            "CMS",
          ],
          d: true,
          e: "5/8/2024",
        },
        {
          a: "Cox Automotive | Irvine, California",
          b: "Software Engineer I",
          c: [
            "BS",
            "C#",
            "C++",
            "OOP",
            "AWS",
            "SQL",
            "NoSQL",
            "React.js",
            ".NET",
            "Agile",
            "Scrum",
          ],
          d: true,
          e: "5/8/2024",
        },
        {
          a: "Crowns Now Inc | Remote",
          b: "Web Developer",
          c: [
            "1 year experience",
            "CSS",
            "Angular",
            "HTML",
            "React",
            "JavaScript",
            "UI/UX",
            "Azure",
          ],
          d: true,
          e: "5/9/2024",
        },
        {
          a: "Microsoft | Redmond, Washington",
          b: "Software Engineer",
          c: [
            "BS",
            "C",
            "C++",
            "C#",
            "Java",
            "JavaScript",
            "Python",
            "Azure",
            "AWS",
            "GCP",
          ],
          d: true,
          e: "5/9/2024",
        },
        {
          a: "Robert Half | Los Angeles, California",
          b: "Software Engineer",
          c: [
            "Python",
            "API",
            "Apache",
            "C++",
            "Database",
            "Hibernate",
            "ORM",
            "AB Testing",
            "Ajax",
            "ASP.NET",
            "CSS",
            "JavaScript",
          ],
          d: true,
          e: "5/9/2024",
        },
        {
          a: "Alpine Data Solutions | Salt Lake City, Utah",
          b: "Full Stack Developer",
          c: [
            "2+ years exp",
            "Java",
            "Angular",
            "ORMs",
            "Postres",
            "SQL Server",
          ],
          d: true,
          e: "5/11/2024",
        },
        {
          a: "NTS - National Taxi Services | Los Angeles, California",
          b: "Full Stack Software Engineer",
          c: [
            "3+ years exp",
            ".NET",
            "SQL",
            "AWS",
            "API",
            "BS",
            "Testing",
            "Documenting",
            "Bugs",
          ],
          d: true,
          e: "5/11/2024",
        },
        {
          a: "Exelon Corporation | Villa Park, Illinois",
          b: "Software Engineer (L1) - Chicago area",
          c: [
            "BS",
            "2-5 years exp",
            "Java",
            ".Net",
            "C#",
            "html",
            "Angular",
            "typescript",
            "ACID",
            "Relational Database",
            "APIs",
            "Troubleshooting",
            "Windows",
            "Solaris",
            "Linux",
            "SCRUM",
            "Kanban",
            "Agile",
            "MS",
            "Test-driven development",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Engtal | North Billerica, Michigan",
          b: "C# Software Engineer II",
          c: [
            "BS",
            "3+ years exp",
            "C#",
            "Visual Studio",
            "Agile",
            "Scrum",
            "C++",
            "Robotics",
            "Electro-mechanical systems",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "firstPRO, Inc. | Boston, Massachusetts",
          b: "Software Engineer (C#, .NET)",
          c: [
            "BS",
            "2+ years exp",
            "C#",
            ".NET",
            "Debug",
            "Troubleshoot",
            "Relational databases",
            "Web applications",
            "Agile",
            "Git",
            "RESTful API",
            "Azure",
            "AWS",
            "ASP.NET",
            "Entity Framework",
            "MVC",
            "React",
            "Vue.js",
            "Kubernetes",
            "Docker",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Stashlete, Inc. | Atlanta, Georgia (Remote)",
          b: "Full Stack Developer",
          c: [
            "API",
            "Troubleshoot",
            "Debug",
            "Desktop and mobile applications",
            "HTML",
            "CSS",
            "JavaScript",
            "XML",
            "jQuery",
            "C#",
            "Java",
            "Python",
            "Angular",
            "React",
            "Node.js",
            "MySQL",
            "MongoDB",
            "Apache",
            "UI/UX",
            "BS",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Coforge | Atlanta, Georgia",
          b: "C++ Developer with C# & Insurance experience",
          c: [
            "C++",
            "CLI",
            "MS MVC (razor .cshtml)",
            "C#",
            "Javascript",
            "HTML/CSS",
            "SQL",
            "MS Visual Studio",
            "MS .Net framework",
            "WCF service",
            "REST service",
            "WIX for installers",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Finturf | Glendale, California",
          b: "Full Stack Developer",
          c: ["HTML", "CSS", "JavaScript", "SQL", "REST API", "Git", "Tableau"],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Trinus Corporation | Newport Beach, California",
          b: "Software Developer",
          c: [
            "Java",
            "Spring Boot",
            "Micronaut",
            "Containers",
            "Debug",
            "OOA",
            "OOD",
            "REST",
            "SOAP",
            "CI/CD",
            "GIT",
            "Azure DevOps",
            "SonarQube",
            "Unit Testing",
            "API",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Closet World | Whittier, California",
          b: "Software Engineer",
          c: [
            "BS",
            "2+ years exp",
            "SQL",
            "JavaScript",
            "VBS",
            "Python",
            "Bash",
            "HTML",
            "xml",
            "wml",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Industry Software | Arcadia, California",
          b: "Software Developer Intern",
          c: [
            "JavaScript",
            "HTML",
            "CSS",
            "Python",
            "Django",
            "UX/UI",
            "BS",
            "MySQL",
            "MongoDB",
            "Scripting",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Zoom Video Communications | San Jose, California",
          b: "Software Engineer",
          c: [
            "BS",
            "C",
            "C++",
            "2 years exp",
            "WinDbg",
            "Visual Studio",
            "Multi-thread",
            "Multi-processes",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Trans Astronautica Corporation | Los Angeles, California",
          b: "Software Developer",
          c: [
            "BS",
            "Python",
            "Rust",
            "C++",
            "Kubernetes",
            "DevOps",
            "GitLab",
            "Linux",
            "Windows",
            "macOS",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "AssistRx | Irvine, California",
          b: "Software Developer w Angular ( remote )",
          c: [
            ".NET",
            ".NET Core",
            "ASP.NET",
            "C#",
            "Unit Tests",
            "User Stories",
            "Use Cases",
            "Design Patterns",
            "Microservices",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "SpaceX | Hawthorne, California",
          b: "Full Stack Software Engineer (Starlink)",
          c: [
            "BS",
            "1+ years exp",
            "Python",
            "C#",
            "Go",
            ".NET",
            "Scala",
            "Java",
            "Docker",
            "Kubernetes",
            "React",
            "Angular",
            "JavaScript",
            "PostgreSQL",
            "SQL Server",
            "CI/CD",
            "Gradle",
            "pip",
            "npm",
            "UNIX",
            "CSS",
            "HTML",
            "TypeScript",
            ".NET Core",
            "Microservices",
          ],
          d: true,
          e: "5/12/2024",
        },
        {
          a: "Samsara | United Kingdom (remote)",
          b: "Software Engineer, Full Stack",
          c: [
            "GoLang",
            "GraphQL",
            "Typescript",
            "React",
            "ReactNative",
            "2+ years exp",
          ],
          d: false,
          e: "5/12/2024",
          f: "5/14/2024",
        },
        {
          a: "Amazon.com Services LLC | Seattle, Washington",
          b: "Software Development Engineer, Mesa Terra",
          c: [
            "Java",
            "C++",
            "C#",
            "BS",
            "1+ years experience",
            "C",
            "Python",
            "Data Structures",
            "Algorithm Design",
            "Problem Solving",
            "Complexity Analysis",
            "Node JS",
            "SDLC",
            "Version Control",
            "Agile",
            "Code Reviews",
            "Test-Driven Development",
            "Continuous Deployment",
          ],
          d: true,
          e: "5/13/2024",
        },
        {
          a: "Deloitte | Rosslyn, Virginia",
          b: "Full Stack Developer",
          c: [
            "BS",
            "Active Secret or Top Secret Clearance",
            "Travel up to 25%",
            "2+ years exp",
            "Java",
            "Spring",
            "Node.js",
            "Frontend",
            "JavaScript",
            "Angular",
            "React",
            "RESTful API",
            "Microservice",
          ],
          d: true,
          e: "5/13/2024",
        },
        {
          a: "Bluebeam | Pasadena, California",
          b: "Software Engineer 2",
          c: [
            ".NET",
            "C#",
            "Desktop development",
            "SDLC",
            "Unit Tests",
            "UX/UI",
            "Daily Standups",
            "Sprint Planning",
            "Design Documents",
            "Deployment",
          ],
          d: true,
          e: "5/13/2024",
          g: "https://career55.sapsf.eu/career?company=nemetschek&site=&lang=en_US&login_ns=login&loginFlowRequired=true&showLogOutMsg=true&brandUrl=&_s.crb=KsT3K8flYTlJ2YnINzPL7H36Vuo0069bfvdogKj0Jb8%253d",
        },
        {
          a: "Capgemini Engineering | Ontario, California",
          b: "Software Engineer - UIQ Test Automation",
          c: ["Test Automation", "QA"],
          d: true,
          e: "5/13/2024",
        },
        {
          a: "CivicEye | Charlotte, North Carolina",
          b: "Software Engineer I",
          c: [
            "HTML",
            "CSS",
            "JavaScript",
            "Databases",
            "GitHub",
            "BS",
            "1-3 years exp",
            "Agile",
          ],
          d: true,
          e: "5/14/2024",
        },
        {
          a: "Jobot | Minneapolis, Minnesota",
          b: ".NET Developer",
          c: [
            "C#",
            ".NET",
            "Visual Studio",
            "Code Reviews",
            "BS",
            ".NET Core",
            "OOA",
            "OOD",
            "Architecture",
          ],
          d: true,
          e: "5/14/2024",
        },
        {
          a: "Bright Digital Solutions | Los Angeles, California",
          b: "Entry-Level Software Engineer - Remote",
          c: [
            "BS",
            "Data Structures",
            "Algorithms",
            "Java",
            "Python",
            "C++",
            "HTML",
            "CSS",
            "JavaScript",
            "React",
            "Angular",
          ],
          d: true,
          e: "5/14/2024",
        },
        {
          a: "CNA National | Scottsdale, Arizona",
          b: "Software Engineer II",
          c: [
            "BS",
            "2+ years exp",
            "Java",
            "Angular",
            "Spring Framework",
            "Spring Boot",
            "REST",
            "Microservices",
            "Junit",
            "Mockito",
            "UI Design",
            "HTML",
            "CSS",
            "JavaScript",
            "SQL",
            "jQuery",
            "Karma",
            "Jasmine",
            "JSP",
            "Git",
            "Kubernetes",
            "Apache Camel",
            "RabbitMQ",
            "Drupal",
            "Eclipse",
            "STS",
            "WebStorm",
            "PL/SQL",
            "Jira",
            "SDLC",
          ],
          d: true,
          e: "5/14/2024",
        },
        {
          a: "Phoenix Recruitment | Chicago, Illinois",
          b: "Website Developer",
          c: ["HTML", "CSS", "Databases", "1+ years exp", "OOP", "SEO", "BS"],
          d: true,
          e: "5/14/2024",
        },
        {
          a: "StockX | Remote",
          b: "Associate Software Development Engineer in Test",
          c: [
            "2-3 years exp",
            "OOP",
            "C#",
            "Java",
            "TypeScript",
            "Web & Mobile applications",
            "QA",
            "Unit Tests",
            "Agile",
            "Scrum",
            "Frontend",
            "Backend",
            "CI/CD",
            "Github",
            "Debugging",
            "Spring Planning",
            "Sprint Grooming",
          ],
          d: true,
          e: "5/14/2024",
        },
        {
          a: "McDonald's Corporation | Chicago, Illinois",
          b: "Software Engineer II - C/C++ [Remote]",
          c: [
            "2+ years exp",
            "C",
            "C++",
            "C#",
            ".NET",
            "Architecture",
            "Design Patterns",
            "Scaling",
            "Reliability",
            "BS",
            "Data Structures",
            "Algorithm Analysis",
            "Agile",
            "OOP",
          ],
          d: true,
          e: "5/14/2024",
        },
      ],
      preferred_companies: [
        "SpaceX",
        "Meta",
        "NASA",
        "Apple",
        "Netflix",
        "Playstation",
        "Google",
        "OpenAI",
      ],
    };
  },
  methods: {
    getAppliedVsRejectedStatistics() {
      var hash_map = {};

      for (const job of this.job_apps) {
        // count inprogress and rejections
        if (job.d) this.statistics.num_inprogress++;
        else this.statistics.num_rejections++;

        // count daily jobs applied
        if (job.e in hash_map) hash_map[job.e]++;
        else if (job.e !== undefined) hash_map[job.e] = 1;
      }
      return hash_map;
    },
  },
  mounted() {
    this.job_map = this.getAppliedVsRejectedStatistics();
  },
};
</script>

<style scoped></style>
